// GENERATED FILE.

// package
var Blockly4kids = Blockly4kids || {};

// game images for actor creation
Blockly4kids.gameImages = {};
Blockly4kids.gameImages['Animals'] = [
	[{ src: 'assets/img/Animals/bear-sq.png', width: 50, height: 50 }, 'Animals-bear-sq#assets/img/Animals/bear-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/bear.png', width: 50, height: 50 }, 'Animals-bear#assets/img/Animals/bear.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/buffalo-sq.png', width: 50, height: 50 }, 'Animals-buffalo-sq#assets/img/Animals/buffalo-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/buffalo.png', width: 50, height: 50 }, 'Animals-buffalo#assets/img/Animals/buffalo.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/chick-sq.png', width: 50, height: 50 }, 'Animals-chick-sq#assets/img/Animals/chick-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/chick.png', width: 50, height: 50 }, 'Animals-chick#assets/img/Animals/chick.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/chicken-sq.png', width: 50, height: 50 }, 'Animals-chicken-sq#assets/img/Animals/chicken-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/chicken.png', width: 50, height: 50 }, 'Animals-chicken#assets/img/Animals/chicken.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/cow-sq.png', width: 50, height: 50 }, 'Animals-cow-sq#assets/img/Animals/cow-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/cow.png', width: 50, height: 50 }, 'Animals-cow#assets/img/Animals/cow.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/crocodile-sq.png', width: 50, height: 50 }, 'Animals-crocodile-sq#assets/img/Animals/crocodile-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/crocodile.png', width: 50, height: 50 }, 'Animals-crocodile#assets/img/Animals/crocodile.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/dog-sq.png', width: 50, height: 50 }, 'Animals-dog-sq#assets/img/Animals/dog-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/dog.png', width: 50, height: 50 }, 'Animals-dog#assets/img/Animals/dog.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/duck-sq.png', width: 50, height: 50 }, 'Animals-duck-sq#assets/img/Animals/duck-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/duck.png', width: 50, height: 50 }, 'Animals-duck#assets/img/Animals/duck.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/elephant-sq.png', width: 50, height: 50 }, 'Animals-elephant-sq#assets/img/Animals/elephant-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/elephant.png', width: 50, height: 50 }, 'Animals-elephant#assets/img/Animals/elephant.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/frog-sq.png', width: 50, height: 50 }, 'Animals-frog-sq#assets/img/Animals/frog-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/frog.png', width: 50, height: 50 }, 'Animals-frog#assets/img/Animals/frog.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/giraffe-sq.png', width: 50, height: 50 }, 'Animals-giraffe-sq#assets/img/Animals/giraffe-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/giraffe.png', width: 50, height: 50 }, 'Animals-giraffe#assets/img/Animals/giraffe.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/goat-sq.png', width: 50, height: 50 }, 'Animals-goat-sq#assets/img/Animals/goat-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/goat.png', width: 50, height: 50 }, 'Animals-goat#assets/img/Animals/goat.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/gorilla-sq.png', width: 50, height: 50 }, 'Animals-gorilla-sq#assets/img/Animals/gorilla-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/gorilla.png', width: 50, height: 50 }, 'Animals-gorilla#assets/img/Animals/gorilla.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/hippo-sq.png', width: 50, height: 50 }, 'Animals-hippo-sq#assets/img/Animals/hippo-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/hippo.png', width: 50, height: 50 }, 'Animals-hippo#assets/img/Animals/hippo.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/horse-sq.png', width: 50, height: 50 }, 'Animals-horse-sq#assets/img/Animals/horse-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/horse.png', width: 50, height: 50 }, 'Animals-horse#assets/img/Animals/horse.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/monkey-sq.png', width: 50, height: 50 }, 'Animals-monkey-sq#assets/img/Animals/monkey-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/monkey.png', width: 50, height: 50 }, 'Animals-monkey#assets/img/Animals/monkey.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/moose-sq.png', width: 50, height: 50 }, 'Animals-moose-sq#assets/img/Animals/moose-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/moose.png', width: 50, height: 50 }, 'Animals-moose#assets/img/Animals/moose.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/narwhal-sq.png', width: 50, height: 50 }, 'Animals-narwhal-sq#assets/img/Animals/narwhal-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/narwhal.png', width: 50, height: 50 }, 'Animals-narwhal#assets/img/Animals/narwhal.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/owl-sq.png', width: 50, height: 50 }, 'Animals-owl-sq#assets/img/Animals/owl-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/owl.png', width: 50, height: 50 }, 'Animals-owl#assets/img/Animals/owl.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/panda-sq.png', width: 50, height: 50 }, 'Animals-panda-sq#assets/img/Animals/panda-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/panda.png', width: 50, height: 50 }, 'Animals-panda#assets/img/Animals/panda.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/parrot-sq.png', width: 50, height: 50 }, 'Animals-parrot-sq#assets/img/Animals/parrot-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/parrot.png', width: 50, height: 50 }, 'Animals-parrot#assets/img/Animals/parrot.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/penguin-sq.png', width: 50, height: 50 }, 'Animals-penguin-sq#assets/img/Animals/penguin-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/penguin.png', width: 50, height: 50 }, 'Animals-penguin#assets/img/Animals/penguin.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/pig-sq.png', width: 50, height: 50 }, 'Animals-pig-sq#assets/img/Animals/pig-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/pig.png', width: 50, height: 50 }, 'Animals-pig#assets/img/Animals/pig.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/rabbit-sq.png', width: 50, height: 50 }, 'Animals-rabbit-sq#assets/img/Animals/rabbit-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/rabbit.png', width: 50, height: 50 }, 'Animals-rabbit#assets/img/Animals/rabbit.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/rhino-sq.png', width: 50, height: 50 }, 'Animals-rhino-sq#assets/img/Animals/rhino-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/rhino.png', width: 50, height: 50 }, 'Animals-rhino#assets/img/Animals/rhino.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/sloth-sq.png', width: 50, height: 50 }, 'Animals-sloth-sq#assets/img/Animals/sloth-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/sloth.png', width: 50, height: 50 }, 'Animals-sloth#assets/img/Animals/sloth.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/snake-nu.png', width: 50, height: 50 }, 'Animals-snake-nu#assets/img/Animals/snake-nu.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/snake-sq.png', width: 50, height: 50 }, 'Animals-snake-sq#assets/img/Animals/snake-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/snake.png', width: 50, height: 50 }, 'Animals-snake#assets/img/Animals/snake.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/walrus-sq.png', width: 50, height: 50 }, 'Animals-walrus-sq#assets/img/Animals/walrus-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/walrus.png', width: 50, height: 50 }, 'Animals-walrus#assets/img/Animals/walrus.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/whale-sq.png', width: 50, height: 50 }, 'Animals-whale-sq#assets/img/Animals/whale-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/whale.png', width: 50, height: 50 }, 'Animals-whale#assets/img/Animals/whale.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/zebra-sq.png', width: 50, height: 50 }, 'Animals-zebra-sq#assets/img/Animals/zebra-sq.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Animals/zebra.png', width: 50, height: 50 }, 'Animals-zebra#assets/img/Animals/zebra.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['Background'] = [
	[{ src: 'assets/img/Background/background.png', width: 50, height: 50 }, 'Background-background#assets/img/Background/background.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/bg_blue.png', width: 50, height: 50 }, 'Background-bg-blue#assets/img/Background/bg_blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/bg_green.png', width: 50, height: 50 }, 'Background-bg-green#assets/img/Background/bg_green.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/bg_red.png', width: 50, height: 50 }, 'Background-bg-red#assets/img/Background/bg_red.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/bg_wood.png', width: 50, height: 50 }, 'Background-bg-wood#assets/img/Background/bg_wood.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/dirt.png', width: 50, height: 50 }, 'Background-dirt#assets/img/Background/dirt.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/glass.png', width: 50, height: 50 }, 'Background-glass#assets/img/Background/glass.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/grass 1.png', width: 50, height: 50 }, 'Background-grass-1#assets/img/Background/grass 1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/grass 2.png', width: 50, height: 50 }, 'Background-grass-2#assets/img/Background/grass 2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/ground 1.png', width: 50, height: 50 }, 'Background-ground-1#assets/img/Background/ground 1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/ground 2.png', width: 50, height: 50 }, 'Background-ground-2#assets/img/Background/ground 2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/ground 3.png', width: 50, height: 50 }, 'Background-ground-3#assets/img/Background/ground 3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/ground 4.png', width: 50, height: 50 }, 'Background-ground-4#assets/img/Background/ground 4.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/industrial.png', width: 50, height: 50 }, 'Background-industrial#assets/img/Background/industrial.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/roof.png', width: 50, height: 50 }, 'Background-roof#assets/img/Background/roof.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/sand.png', width: 50, height: 50 }, 'Background-sand#assets/img/Background/sand.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/sky.png', width: 50, height: 50 }, 'Background-sky#assets/img/Background/sky.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/space-blue.png', width: 50, height: 50 }, 'Background-space-blue#assets/img/Background/space-blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/space-no-star.png', width: 50, height: 50 }, 'Background-space-no-star#assets/img/Background/space-no-star.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/space.png', width: 50, height: 50 }, 'Background-space#assets/img/Background/space.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/tile 1.png', width: 50, height: 50 }, 'Background-tile-1#assets/img/Background/tile 1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Background/tile 2.png', width: 50, height: 50 }, 'Background-tile-2#assets/img/Background/tile 2.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['Board'] = [
	[{ src: 'assets/img/Board/dieRed1.png', width: 50, height: 50 }, 'Board-dieRed1#assets/img/Board/dieRed1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed2.png', width: 50, height: 50 }, 'Board-dieRed2#assets/img/Board/dieRed2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed3.png', width: 50, height: 50 }, 'Board-dieRed3#assets/img/Board/dieRed3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed4.png', width: 50, height: 50 }, 'Board-dieRed4#assets/img/Board/dieRed4.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed5.png', width: 50, height: 50 }, 'Board-dieRed5#assets/img/Board/dieRed5.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed6.png', width: 50, height: 50 }, 'Board-dieRed6#assets/img/Board/dieRed6.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed_border1.png', width: 50, height: 50 }, 'Board-dieRed-border1#assets/img/Board/dieRed_border1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed_border2.png', width: 50, height: 50 }, 'Board-dieRed-border2#assets/img/Board/dieRed_border2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed_border3.png', width: 50, height: 50 }, 'Board-dieRed-border3#assets/img/Board/dieRed_border3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed_border4.png', width: 50, height: 50 }, 'Board-dieRed-border4#assets/img/Board/dieRed_border4.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed_border5.png', width: 50, height: 50 }, 'Board-dieRed-border5#assets/img/Board/dieRed_border5.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/dieRed_border6.png', width: 50, height: 50 }, 'Board-dieRed-border6#assets/img/Board/dieRed_border6.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/pieceBlack_border02.png', width: 50, height: 50 }, 'Board-pieceBlack-border02#assets/img/Board/pieceBlack_border02.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/pieceBlack_border11.png', width: 50, height: 50 }, 'Board-pieceBlack-border11#assets/img/Board/pieceBlack_border11.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/pieceWhite_border02.png', width: 50, height: 50 }, 'Board-pieceWhite-border02#assets/img/Board/pieceWhite_border02.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Board/pieceWhite_border11.png', width: 50, height: 50 }, 'Board-pieceWhite-border11#assets/img/Board/pieceWhite_border11.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['Brick'] = [
	[{ src: 'assets/img/Brick/ballBlue.png', width: 50, height: 50 }, 'Brick-ballBlue#assets/img/Brick/ballBlue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/ballGrey.png', width: 50, height: 50 }, 'Brick-ballGrey#assets/img/Brick/ballGrey.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_diamond.png', width: 50, height: 50 }, 'Brick-element-blue-diamond#assets/img/Brick/element_blue_diamond.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_diamond_glossy.png', width: 50, height: 50 }, 'Brick-element-blue-diamond-glossy#assets/img/Brick/element_blue_diamond_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_polygon.png', width: 50, height: 50 }, 'Brick-element-blue-polygon#assets/img/Brick/element_blue_polygon.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_polygon_glossy.png', width: 50, height: 50 }, 'Brick-element-blue-polygon-glossy#assets/img/Brick/element_blue_polygon_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_rectangle.png', width: 50, height: 50 }, 'Brick-element-blue-rectangle#assets/img/Brick/element_blue_rectangle.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_rectangle_glossy.png', width: 50, height: 50 }, 'Brick-element-blue-rectangle-glossy#assets/img/Brick/element_blue_rectangle_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_square.png', width: 50, height: 50 }, 'Brick-element-blue-square#assets/img/Brick/element_blue_square.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_blue_square_glossy.png', width: 50, height: 50 }, 'Brick-element-blue-square-glossy#assets/img/Brick/element_blue_square_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_diamond.png', width: 50, height: 50 }, 'Brick-element-green-diamond#assets/img/Brick/element_green_diamond.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_diamond_glossy.png', width: 50, height: 50 }, 'Brick-element-green-diamond-glossy#assets/img/Brick/element_green_diamond_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_polygon.png', width: 50, height: 50 }, 'Brick-element-green-polygon#assets/img/Brick/element_green_polygon.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_polygon_glossy.png', width: 50, height: 50 }, 'Brick-element-green-polygon-glossy#assets/img/Brick/element_green_polygon_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_rectangle.png', width: 50, height: 50 }, 'Brick-element-green-rectangle#assets/img/Brick/element_green_rectangle.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_rectangle_glossy.png', width: 50, height: 50 }, 'Brick-element-green-rectangle-glossy#assets/img/Brick/element_green_rectangle_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_square.png', width: 50, height: 50 }, 'Brick-element-green-square#assets/img/Brick/element_green_square.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_green_square_glossy.png', width: 50, height: 50 }, 'Brick-element-green-square-glossy#assets/img/Brick/element_green_square_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_diamond.png', width: 50, height: 50 }, 'Brick-element-grey-diamond#assets/img/Brick/element_grey_diamond.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_diamond_glossy.png', width: 50, height: 50 }, 'Brick-element-grey-diamond-glossy#assets/img/Brick/element_grey_diamond_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_polygon.png', width: 50, height: 50 }, 'Brick-element-grey-polygon#assets/img/Brick/element_grey_polygon.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_polygon_glossy.png', width: 50, height: 50 }, 'Brick-element-grey-polygon-glossy#assets/img/Brick/element_grey_polygon_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_rectangle.png', width: 50, height: 50 }, 'Brick-element-grey-rectangle#assets/img/Brick/element_grey_rectangle.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_rectangle_glossy.png', width: 50, height: 50 }, 'Brick-element-grey-rectangle-glossy#assets/img/Brick/element_grey_rectangle_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_square.png', width: 50, height: 50 }, 'Brick-element-grey-square#assets/img/Brick/element_grey_square.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_grey_square_glossy.png', width: 50, height: 50 }, 'Brick-element-grey-square-glossy#assets/img/Brick/element_grey_square_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_cube_glossy.png', width: 50, height: 50 }, 'Brick-element-purple-cube-glossy#assets/img/Brick/element_purple_cube_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_diamond.png', width: 50, height: 50 }, 'Brick-element-purple-diamond#assets/img/Brick/element_purple_diamond.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_diamond_glossy.png', width: 50, height: 50 }, 'Brick-element-purple-diamond-glossy#assets/img/Brick/element_purple_diamond_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_polygon.png', width: 50, height: 50 }, 'Brick-element-purple-polygon#assets/img/Brick/element_purple_polygon.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_polygon_glossy.png', width: 50, height: 50 }, 'Brick-element-purple-polygon-glossy#assets/img/Brick/element_purple_polygon_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_rectangle.png', width: 50, height: 50 }, 'Brick-element-purple-rectangle#assets/img/Brick/element_purple_rectangle.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_rectangle_glossy.png', width: 50, height: 50 }, 'Brick-element-purple-rectangle-glossy#assets/img/Brick/element_purple_rectangle_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_purple_square.png', width: 50, height: 50 }, 'Brick-element-purple-square#assets/img/Brick/element_purple_square.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_diamond.png', width: 50, height: 50 }, 'Brick-element-red-diamond#assets/img/Brick/element_red_diamond.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_diamond_glossy.png', width: 50, height: 50 }, 'Brick-element-red-diamond-glossy#assets/img/Brick/element_red_diamond_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_polygon.png', width: 50, height: 50 }, 'Brick-element-red-polygon#assets/img/Brick/element_red_polygon.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_polygon_glossy.png', width: 50, height: 50 }, 'Brick-element-red-polygon-glossy#assets/img/Brick/element_red_polygon_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_rectangle.png', width: 50, height: 50 }, 'Brick-element-red-rectangle#assets/img/Brick/element_red_rectangle.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_rectangle_glossy.png', width: 50, height: 50 }, 'Brick-element-red-rectangle-glossy#assets/img/Brick/element_red_rectangle_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_square.png', width: 50, height: 50 }, 'Brick-element-red-square#assets/img/Brick/element_red_square.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_red_square_glossy.png', width: 50, height: 50 }, 'Brick-element-red-square-glossy#assets/img/Brick/element_red_square_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_diamond.png', width: 50, height: 50 }, 'Brick-element-yellow-diamond#assets/img/Brick/element_yellow_diamond.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_diamond_glossy.png', width: 50, height: 50 }, 'Brick-element-yellow-diamond-glossy#assets/img/Brick/element_yellow_diamond_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_polygon.png', width: 50, height: 50 }, 'Brick-element-yellow-polygon#assets/img/Brick/element_yellow_polygon.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_polygon_glossy.png', width: 50, height: 50 }, 'Brick-element-yellow-polygon-glossy#assets/img/Brick/element_yellow_polygon_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_rectangle.png', width: 50, height: 50 }, 'Brick-element-yellow-rectangle#assets/img/Brick/element_yellow_rectangle.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_rectangle_glossy.png', width: 50, height: 50 }, 'Brick-element-yellow-rectangle-glossy#assets/img/Brick/element_yellow_rectangle_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_square.png', width: 50, height: 50 }, 'Brick-element-yellow-square#assets/img/Brick/element_yellow_square.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/element_yellow_square_glossy.png', width: 50, height: 50 }, 'Brick-element-yellow-square-glossy#assets/img/Brick/element_yellow_square_glossy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/paddleBlu.png', width: 50, height: 50 }, 'Brick-paddleBlu#assets/img/Brick/paddleBlu.png#w#h-80#cw#ch'],
	[{ src: 'assets/img/Brick/paddleRed.png', width: 50, height: 50 }, 'Brick-paddleRed#assets/img/Brick/paddleRed.png#w#h-80#cw#ch'],
	[{ src: 'assets/img/Brick/particleCartoonStar.png', width: 50, height: 50 }, 'Brick-particleCartoonStar#assets/img/Brick/particleCartoonStar.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/particleSmallStar.png', width: 50, height: 50 }, 'Brick-particleSmallStar#assets/img/Brick/particleSmallStar.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/particleStar.png', width: 50, height: 50 }, 'Brick-particleStar#assets/img/Brick/particleStar.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/selectorA.png', width: 50, height: 50 }, 'Brick-selectorA#assets/img/Brick/selectorA.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/selectorB.png', width: 50, height: 50 }, 'Brick-selectorB#assets/img/Brick/selectorB.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Brick/selectorC.png', width: 50, height: 50 }, 'Brick-selectorC#assets/img/Brick/selectorC.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['PlanetCute'] = [
	[{ src: 'assets/img/PlanetCute/Beetleship.png', width: 50, height: 50 }, 'PlanetCute-Beetleship#assets/img/PlanetCute/Beetleship.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Brown Block.png', width: 50, height: 50 }, 'PlanetCute-Brown-Block#assets/img/PlanetCute/Brown Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Character Boy.png', width: 50, height: 50 }, 'PlanetCute-Character-Boy#assets/img/PlanetCute/Character Boy.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Character Cat Girl.png', width: 50, height: 50 }, 'PlanetCute-Character-Cat-Girl#assets/img/PlanetCute/Character Cat Girl.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Character Horn Girl.png', width: 50, height: 50 }, 'PlanetCute-Character-Horn-Girl#assets/img/PlanetCute/Character Horn Girl.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Character Pink Girl.png', width: 50, height: 50 }, 'PlanetCute-Character-Pink-Girl#assets/img/PlanetCute/Character Pink Girl.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Character Princess Girl.png', width: 50, height: 50 }, 'PlanetCute-Character-Princess-Girl#assets/img/PlanetCute/Character Princess Girl.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Chest Closed.png', width: 50, height: 50 }, 'PlanetCute-Chest-Closed#assets/img/PlanetCute/Chest Closed.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Chest Lid.png', width: 50, height: 50 }, 'PlanetCute-Chest-Lid#assets/img/PlanetCute/Chest Lid.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Chest Open.png', width: 50, height: 50 }, 'PlanetCute-Chest-Open#assets/img/PlanetCute/Chest Open.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Dirt Block.png', width: 50, height: 50 }, 'PlanetCute-Dirt-Block#assets/img/PlanetCute/Dirt Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Door Tall Closed.png', width: 50, height: 50 }, 'PlanetCute-Door-Tall-Closed#assets/img/PlanetCute/Door Tall Closed.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Door Tall Open.png', width: 50, height: 50 }, 'PlanetCute-Door-Tall-Open#assets/img/PlanetCute/Door Tall Open.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Enemy Bug.png', width: 50, height: 50 }, 'PlanetCute-Enemy-Bug#assets/img/PlanetCute/Enemy Bug.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Gem Blue.png', width: 50, height: 50 }, 'PlanetCute-Gem-Blue#assets/img/PlanetCute/Gem Blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Gem Green.png', width: 50, height: 50 }, 'PlanetCute-Gem-Green#assets/img/PlanetCute/Gem Green.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Gem Orange.png', width: 50, height: 50 }, 'PlanetCute-Gem-Orange#assets/img/PlanetCute/Gem Orange.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Grass Block.png', width: 50, height: 50 }, 'PlanetCute-Grass-Block#assets/img/PlanetCute/Grass Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Heart.png', width: 50, height: 50 }, 'PlanetCute-Heart#assets/img/PlanetCute/Heart.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Key.png', width: 50, height: 50 }, 'PlanetCute-Key#assets/img/PlanetCute/Key.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Plain Block.png', width: 50, height: 50 }, 'PlanetCute-Plain-Block#assets/img/PlanetCute/Plain Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Ramp East.png', width: 50, height: 50 }, 'PlanetCute-Ramp-East#assets/img/PlanetCute/Ramp East.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Ramp North.png', width: 50, height: 50 }, 'PlanetCute-Ramp-North#assets/img/PlanetCute/Ramp North.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Ramp South.png', width: 50, height: 50 }, 'PlanetCute-Ramp-South#assets/img/PlanetCute/Ramp South.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Ramp West.png', width: 50, height: 50 }, 'PlanetCute-Ramp-West#assets/img/PlanetCute/Ramp West.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Rock.png', width: 50, height: 50 }, 'PlanetCute-Rock#assets/img/PlanetCute/Rock.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof East.png', width: 50, height: 50 }, 'PlanetCute-Roof-East#assets/img/PlanetCute/Roof East.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof North East.png', width: 50, height: 50 }, 'PlanetCute-Roof-North-East#assets/img/PlanetCute/Roof North East.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof North West.png', width: 50, height: 50 }, 'PlanetCute-Roof-North-West#assets/img/PlanetCute/Roof North West.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof North.png', width: 50, height: 50 }, 'PlanetCute-Roof-North#assets/img/PlanetCute/Roof North.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof South East.png', width: 50, height: 50 }, 'PlanetCute-Roof-South-East#assets/img/PlanetCute/Roof South East.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof South West.png', width: 50, height: 50 }, 'PlanetCute-Roof-South-West#assets/img/PlanetCute/Roof South West.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof South.png', width: 50, height: 50 }, 'PlanetCute-Roof-South#assets/img/PlanetCute/Roof South.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Roof West.png', width: 50, height: 50 }, 'PlanetCute-Roof-West#assets/img/PlanetCute/Roof West.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Selector.png', width: 50, height: 50 }, 'PlanetCute-Selector#assets/img/PlanetCute/Selector.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Star.png', width: 50, height: 50 }, 'PlanetCute-Star#assets/img/PlanetCute/Star.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Stone Block Tall.png', width: 50, height: 50 }, 'PlanetCute-Stone-Block-Tall#assets/img/PlanetCute/Stone Block Tall.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Stone Block.png', width: 50, height: 50 }, 'PlanetCute-Stone-Block#assets/img/PlanetCute/Stone Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Tree Short.png', width: 50, height: 50 }, 'PlanetCute-Tree-Short#assets/img/PlanetCute/Tree Short.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Tree Tall.png', width: 50, height: 50 }, 'PlanetCute-Tree-Tall#assets/img/PlanetCute/Tree Tall.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Tree Ugly.png', width: 50, height: 50 }, 'PlanetCute-Tree-Ugly#assets/img/PlanetCute/Tree Ugly.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Wall Block Tall.png', width: 50, height: 50 }, 'PlanetCute-Wall-Block-Tall#assets/img/PlanetCute/Wall Block Tall.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Wall Block.png', width: 50, height: 50 }, 'PlanetCute-Wall-Block#assets/img/PlanetCute/Wall Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Water Block.png', width: 50, height: 50 }, 'PlanetCute-Water-Block#assets/img/PlanetCute/Water Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Window Tall.png', width: 50, height: 50 }, 'PlanetCute-Window-Tall#assets/img/PlanetCute/Window Tall.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/Wood Block.png', width: 50, height: 50 }, 'PlanetCute-Wood-Block#assets/img/PlanetCute/Wood Block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/octopus.png', width: 50, height: 50 }, 'PlanetCute-octopus#assets/img/PlanetCute/octopus.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/planet.png', width: 50, height: 50 }, 'PlanetCute-planet#assets/img/PlanetCute/planet.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/PlanetCute/rocketship.png', width: 50, height: 50 }, 'PlanetCute-rocketship#assets/img/PlanetCute/rocketship.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['Platformer'] = [
	[{ src: 'assets/img/Platformer/Cloud1.png', width: 50, height: 50 }, 'Platformer-Cloud1#assets/img/Platformer/Cloud1.png#w#h-40#cw#h-20'],
	[{ src: 'assets/img/Platformer/Cloud2.png', width: 50, height: 50 }, 'Platformer-Cloud2#assets/img/Platformer/Cloud2.png#w#h-40#cw#h-20'],
	[{ src: 'assets/img/Platformer/Cloud3.png', width: 50, height: 50 }, 'Platformer-Cloud3#assets/img/Platformer/Cloud3.png#w#h-40#cw#h-20'],
	[{ src: 'assets/img/Platformer/block.png', width: 50, height: 50 }, 'Platformer-block#assets/img/Platformer/block.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/bonus.png', width: 50, height: 50 }, 'Platformer-bonus#assets/img/Platformer/bonus.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/bonus_used.png', width: 50, height: 50 }, 'Platformer-bonus-used#assets/img/Platformer/bonus_used.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/bush.png', width: 50, height: 50 }, 'Platformer-bush#assets/img/Platformer/bush.png#w#h-15#cw#h-10'],
	[{ src: 'assets/img/Platformer/coin.png', width: 50, height: 50 }, 'Platformer-coin#assets/img/Platformer/coin.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/crate.png', width: 50, height: 50 }, 'Platformer-crate#assets/img/Platformer/crate.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/fence.png', width: 50, height: 50 }, 'Platformer-fence#assets/img/Platformer/fence.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/fence_broken.png', width: 50, height: 50 }, 'Platformer-fence-broken#assets/img/Platformer/fence_broken.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/fly_dead.png', width: 50, height: 50 }, 'Platformer-fly-dead#assets/img/Platformer/fly_dead.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/fly_fly.png', width: 50, height: 50 }, 'Platformer-fly-fly#assets/img/Platformer/fly_fly.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/fly_normal.png', width: 50, height: 50 }, 'Platformer-fly-normal#assets/img/Platformer/fly_normal.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/front.png', width: 50, height: 50 }, 'Platformer-front#assets/img/Platformer/front.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/grass.png', width: 50, height: 50 }, 'Platformer-grass#assets/img/Platformer/grass.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/ground.png', width: 50, height: 50 }, 'Platformer-ground#assets/img/Platformer/ground.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/ground_cave.png', width: 50, height: 50 }, 'Platformer-ground-cave#assets/img/Platformer/ground_cave.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/hill_long.png', width: 50, height: 50 }, 'Platformer-hill-long#assets/img/Platformer/hill_long.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/hill_short.png', width: 50, height: 50 }, 'Platformer-hill-short#assets/img/Platformer/hill_short.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/jump.png', width: 50, height: 50 }, 'Platformer-jump#assets/img/Platformer/jump.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/shroom.png', width: 50, height: 50 }, 'Platformer-shroom#assets/img/Platformer/shroom.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/side.png', width: 50, height: 50 }, 'Platformer-side#assets/img/Platformer/side.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/slime_dead.png', width: 50, height: 50 }, 'Platformer-slime-dead#assets/img/Platformer/slime_dead.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/slime_normal.png', width: 50, height: 50 }, 'Platformer-slime-normal#assets/img/Platformer/slime_normal.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/slime_walk.png', width: 50, height: 50 }, 'Platformer-slime-walk#assets/img/Platformer/slime_walk.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/spikes.png', width: 50, height: 50 }, 'Platformer-spikes#assets/img/Platformer/spikes.png#w#h#cw#ch'],
	[{ src: 'assets/img/Platformer/walk_sheet.png', width: 50, height: 50 }, 'Platformer-walk-sheet#assets/img/Platformer/walk_sheet.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/Platformer/water.png', width: 50, height: 50 }, 'Platformer-water#assets/img/Platformer/water.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['ShootingGallery'] = [
	[{ src: 'assets/img/ShootingGallery/crosshair_blue_large.png', width: 50, height: 50 }, 'ShootingGallery-crosshair-blue-large#assets/img/ShootingGallery/crosshair_blue_large.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/crosshair_blue_small.png', width: 50, height: 50 }, 'ShootingGallery-crosshair-blue-small#assets/img/ShootingGallery/crosshair_blue_small.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/crosshair_outline_large.png', width: 50, height: 50 }, 'ShootingGallery-crosshair-outline-large#assets/img/ShootingGallery/crosshair_outline_large.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/crosshair_outline_small.png', width: 50, height: 50 }, 'ShootingGallery-crosshair-outline-small#assets/img/ShootingGallery/crosshair_outline_small.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/crosshair_red_large.png', width: 50, height: 50 }, 'ShootingGallery-crosshair-red-large#assets/img/ShootingGallery/crosshair_red_large.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/crosshair_red_small.png', width: 50, height: 50 }, 'ShootingGallery-crosshair-red-small#assets/img/ShootingGallery/crosshair_red_small.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/curtain.png', width: 50, height: 50 }, 'ShootingGallery-curtain#assets/img/ShootingGallery/curtain.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/curtain_rope.png', width: 50, height: 50 }, 'ShootingGallery-curtain-rope#assets/img/ShootingGallery/curtain_rope.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/curtain_straight.png', width: 50, height: 50 }, 'ShootingGallery-curtain-straight#assets/img/ShootingGallery/curtain_straight.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/curtain_top.png', width: 50, height: 50 }, 'ShootingGallery-curtain-top#assets/img/ShootingGallery/curtain_top.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/duck_outline_back.png', width: 50, height: 50 }, 'ShootingGallery-duck-outline-back#assets/img/ShootingGallery/duck_outline_back.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/duck_outline_brown.png', width: 50, height: 50 }, 'ShootingGallery-duck-outline-brown#assets/img/ShootingGallery/duck_outline_brown.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/duck_outline_target_brown.png', width: 50, height: 50 }, 'ShootingGallery-duck-outline-target-brown#assets/img/ShootingGallery/duck_outline_target_brown.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/duck_outline_target_white.png', width: 50, height: 50 }, 'ShootingGallery-duck-outline-target-white#assets/img/ShootingGallery/duck_outline_target_white.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/duck_outline_target_yellow.png', width: 50, height: 50 }, 'ShootingGallery-duck-outline-target-yellow#assets/img/ShootingGallery/duck_outline_target_yellow.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/duck_outline_white.png', width: 50, height: 50 }, 'ShootingGallery-duck-outline-white#assets/img/ShootingGallery/duck_outline_white.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/duck_outline_yellow.png', width: 50, height: 50 }, 'ShootingGallery-duck-outline-yellow#assets/img/ShootingGallery/duck_outline_yellow.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/grass1.png', width: 50, height: 50 }, 'ShootingGallery-grass1#assets/img/ShootingGallery/grass1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/grass2.png', width: 50, height: 50 }, 'ShootingGallery-grass2#assets/img/ShootingGallery/grass2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/icon_bullet_gold_long.png', width: 50, height: 50 }, 'ShootingGallery-icon-bullet-gold-long#assets/img/ShootingGallery/icon_bullet_gold_long.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/icon_bullet_gold_short.png', width: 50, height: 50 }, 'ShootingGallery-icon-bullet-gold-short#assets/img/ShootingGallery/icon_bullet_gold_short.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/icon_bullet_silver_long.png', width: 50, height: 50 }, 'ShootingGallery-icon-bullet-silver-long#assets/img/ShootingGallery/icon_bullet_silver_long.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/icon_bullet_silver_short.png', width: 50, height: 50 }, 'ShootingGallery-icon-bullet-silver-short#assets/img/ShootingGallery/icon_bullet_silver_short.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/icon_duck.png', width: 50, height: 50 }, 'ShootingGallery-icon-duck#assets/img/ShootingGallery/icon_duck.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/icon_target.png', width: 50, height: 50 }, 'ShootingGallery-icon-target#assets/img/ShootingGallery/icon_target.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/rifle.png', width: 50, height: 50 }, 'ShootingGallery-rifle#assets/img/ShootingGallery/rifle.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/rifle_red.png', width: 50, height: 50 }, 'ShootingGallery-rifle-red#assets/img/ShootingGallery/rifle_red.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/shot_blue_large.png', width: 50, height: 50 }, 'ShootingGallery-shot-blue-large#assets/img/ShootingGallery/shot_blue_large.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/shot_blue_small.png', width: 50, height: 50 }, 'ShootingGallery-shot-blue-small#assets/img/ShootingGallery/shot_blue_small.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/stick_metal_outline.png', width: 50, height: 50 }, 'ShootingGallery-stick-metal-outline#assets/img/ShootingGallery/stick_metal_outline.png#w - 15#h#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/stick_metal_outline_broken.png', width: 50, height: 50 }, 'ShootingGallery-stick-metal-outline-broken#assets/img/ShootingGallery/stick_metal_outline_broken.png#w#h#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/stick_woodFixed_outline.png', width: 50, height: 50 }, 'ShootingGallery-stick-woodFixed-outline#assets/img/ShootingGallery/stick_woodFixed_outline.png#w - 15#h#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/stick_wood_outline.png', width: 50, height: 50 }, 'ShootingGallery-stick-wood-outline#assets/img/ShootingGallery/stick_wood_outline.png#w - 15#h#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/stick_wood_outline_broken.png', width: 50, height: 50 }, 'ShootingGallery-stick-wood-outline-broken#assets/img/ShootingGallery/stick_wood_outline_broken.png#w#h#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/target_colored_outline.png', width: 50, height: 50 }, 'ShootingGallery-target-colored-outline#assets/img/ShootingGallery/target_colored_outline.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/target_red1_outline.png', width: 50, height: 50 }, 'ShootingGallery-target-red1-outline#assets/img/ShootingGallery/target_red1_outline.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/target_red2_outline.png', width: 50, height: 50 }, 'ShootingGallery-target-red2-outline#assets/img/ShootingGallery/target_red2_outline.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/text_gameover.png', width: 50, height: 50 }, 'ShootingGallery-text-gameover#assets/img/ShootingGallery/text_gameover.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/text_go.png', width: 50, height: 50 }, 'ShootingGallery-text-go#assets/img/ShootingGallery/text_go.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/text_ready.png', width: 50, height: 50 }, 'ShootingGallery-text-ready#assets/img/ShootingGallery/text_ready.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/text_score.png', width: 50, height: 50 }, 'ShootingGallery-text-score#assets/img/ShootingGallery/text_score.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/text_timeup.png', width: 50, height: 50 }, 'ShootingGallery-text-timeup#assets/img/ShootingGallery/text_timeup.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/tree_oak.png', width: 50, height: 50 }, 'ShootingGallery-tree-oak#assets/img/ShootingGallery/tree_oak.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/tree_pine.png', width: 50, height: 50 }, 'ShootingGallery-tree-pine#assets/img/ShootingGallery/tree_pine.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/upcloud1.png', width: 50, height: 50 }, 'ShootingGallery-upcloud1#assets/img/ShootingGallery/upcloud1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/upcloud2.png', width: 50, height: 50 }, 'ShootingGallery-upcloud2#assets/img/ShootingGallery/upcloud2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/water1.png', width: 50, height: 50 }, 'ShootingGallery-water1#assets/img/ShootingGallery/water1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/ShootingGallery/water2.png', width: 50, height: 50 }, 'ShootingGallery-water2#assets/img/ShootingGallery/water2.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['SpaceArt'] = [
	[{ src: 'assets/img/SpaceArt/enemyBlack1.png', width: 50, height: 50 }, 'SpaceArt-enemyBlack1#assets/img/SpaceArt/enemyBlack1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlack2.png', width: 50, height: 50 }, 'SpaceArt-enemyBlack2#assets/img/SpaceArt/enemyBlack2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlack3.png', width: 50, height: 50 }, 'SpaceArt-enemyBlack3#assets/img/SpaceArt/enemyBlack3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlack4.png', width: 50, height: 50 }, 'SpaceArt-enemyBlack4#assets/img/SpaceArt/enemyBlack4.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlack5.png', width: 50, height: 50 }, 'SpaceArt-enemyBlack5#assets/img/SpaceArt/enemyBlack5.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlue1.png', width: 50, height: 50 }, 'SpaceArt-enemyBlue1#assets/img/SpaceArt/enemyBlue1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlue2.png', width: 50, height: 50 }, 'SpaceArt-enemyBlue2#assets/img/SpaceArt/enemyBlue2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlue3.png', width: 50, height: 50 }, 'SpaceArt-enemyBlue3#assets/img/SpaceArt/enemyBlue3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlue4.png', width: 50, height: 50 }, 'SpaceArt-enemyBlue4#assets/img/SpaceArt/enemyBlue4.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyBlue5.png', width: 50, height: 50 }, 'SpaceArt-enemyBlue5#assets/img/SpaceArt/enemyBlue5.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyGreen1.png', width: 50, height: 50 }, 'SpaceArt-enemyGreen1#assets/img/SpaceArt/enemyGreen1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyGreen2.png', width: 50, height: 50 }, 'SpaceArt-enemyGreen2#assets/img/SpaceArt/enemyGreen2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyGreen3.png', width: 50, height: 50 }, 'SpaceArt-enemyGreen3#assets/img/SpaceArt/enemyGreen3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyGreen4.png', width: 50, height: 50 }, 'SpaceArt-enemyGreen4#assets/img/SpaceArt/enemyGreen4.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyGreen5.png', width: 50, height: 50 }, 'SpaceArt-enemyGreen5#assets/img/SpaceArt/enemyGreen5.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyRed1.png', width: 50, height: 50 }, 'SpaceArt-enemyRed1#assets/img/SpaceArt/enemyRed1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyRed2.png', width: 50, height: 50 }, 'SpaceArt-enemyRed2#assets/img/SpaceArt/enemyRed2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyRed3.png', width: 50, height: 50 }, 'SpaceArt-enemyRed3#assets/img/SpaceArt/enemyRed3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyRed4.png', width: 50, height: 50 }, 'SpaceArt-enemyRed4#assets/img/SpaceArt/enemyRed4.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyRed5.png', width: 50, height: 50 }, 'SpaceArt-enemyRed5#assets/img/SpaceArt/enemyRed5.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/enemyShip.png', width: 50, height: 50 }, 'SpaceArt-enemyShip#assets/img/SpaceArt/enemyShip.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/laserGreen.png', width: 50, height: 50 }, 'SpaceArt-laserGreen#assets/img/SpaceArt/laserGreen.png#w-24#h-24#cw#ch'],
	[{ src: 'assets/img/SpaceArt/laserGreenShot.png', width: 50, height: 50 }, 'SpaceArt-laserGreenShot#assets/img/SpaceArt/laserGreenShot.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/laserRed.png', width: 50, height: 50 }, 'SpaceArt-laserRed#assets/img/SpaceArt/laserRed.png#w-24#h-24#cw#ch'],
	[{ src: 'assets/img/SpaceArt/laserRedShot.png', width: 50, height: 50 }, 'SpaceArt-laserRedShot#assets/img/SpaceArt/laserRedShot.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/meteorBrown_big2.png', width: 50, height: 50 }, 'SpaceArt-meteorBrown-big2#assets/img/SpaceArt/meteorBrown_big2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/meteorBrown_med3.png', width: 50, height: 50 }, 'SpaceArt-meteorBrown-med3#assets/img/SpaceArt/meteorBrown_med3.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/meteorBrown_tiny2.png', width: 50, height: 50 }, 'SpaceArt-meteorBrown-tiny2#assets/img/SpaceArt/meteorBrown_tiny2.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/meteorSmall.png', width: 50, height: 50 }, 'SpaceArt-meteorSmall#assets/img/SpaceArt/meteorSmall.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/nebula.png', width: 50, height: 50 }, 'SpaceArt-nebula#assets/img/SpaceArt/nebula.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/pill_blue.png', width: 50, height: 50 }, 'SpaceArt-pill-blue#assets/img/SpaceArt/pill_blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/pill_green.png', width: 50, height: 50 }, 'SpaceArt-pill-green#assets/img/SpaceArt/pill_green.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/pill_red.png', width: 50, height: 50 }, 'SpaceArt-pill-red#assets/img/SpaceArt/pill_red.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/pill_yellow.png', width: 50, height: 50 }, 'SpaceArt-pill-yellow#assets/img/SpaceArt/pill_yellow.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerLife1_blue.png', width: 50, height: 50 }, 'SpaceArt-playerLife1-blue#assets/img/SpaceArt/playerLife1_blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerLife1_green.png', width: 50, height: 50 }, 'SpaceArt-playerLife1-green#assets/img/SpaceArt/playerLife1_green.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerLife1_orange.png', width: 50, height: 50 }, 'SpaceArt-playerLife1-orange#assets/img/SpaceArt/playerLife1_orange.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip1_blue.png', width: 50, height: 50 }, 'SpaceArt-playerShip1-blue#assets/img/SpaceArt/playerShip1_blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip1_green.png', width: 50, height: 50 }, 'SpaceArt-playerShip1-green#assets/img/SpaceArt/playerShip1_green.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip1_orange.png', width: 50, height: 50 }, 'SpaceArt-playerShip1-orange#assets/img/SpaceArt/playerShip1_orange.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip2_blue.png', width: 50, height: 50 }, 'SpaceArt-playerShip2-blue#assets/img/SpaceArt/playerShip2_blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip2_green.png', width: 50, height: 50 }, 'SpaceArt-playerShip2-green#assets/img/SpaceArt/playerShip2_green.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip2_orange.png', width: 50, height: 50 }, 'SpaceArt-playerShip2-orange#assets/img/SpaceArt/playerShip2_orange.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip3_blue.png', width: 50, height: 50 }, 'SpaceArt-playerShip3-blue#assets/img/SpaceArt/playerShip3_blue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip3_green.png', width: 50, height: 50 }, 'SpaceArt-playerShip3-green#assets/img/SpaceArt/playerShip3_green.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/playerShip3_orange.png', width: 50, height: 50 }, 'SpaceArt-playerShip3-orange#assets/img/SpaceArt/playerShip3_orange.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/shield.png', width: 50, height: 50 }, 'SpaceArt-shield#assets/img/SpaceArt/shield.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/shield_bronze.png', width: 50, height: 50 }, 'SpaceArt-shield-bronze#assets/img/SpaceArt/shield_bronze.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/shield_gold.png', width: 50, height: 50 }, 'SpaceArt-shield-gold#assets/img/SpaceArt/shield_gold.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/shield_silver.png', width: 50, height: 50 }, 'SpaceArt-shield-silver#assets/img/SpaceArt/shield_silver.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_001.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-001#assets/img/SpaceArt/spaceAstronauts_001.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_002.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-002#assets/img/SpaceArt/spaceAstronauts_002.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_003.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-003#assets/img/SpaceArt/spaceAstronauts_003.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_004.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-004#assets/img/SpaceArt/spaceAstronauts_004.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_005.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-005#assets/img/SpaceArt/spaceAstronauts_005.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_006.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-006#assets/img/SpaceArt/spaceAstronauts_006.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_007.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-007#assets/img/SpaceArt/spaceAstronauts_007.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_008.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-008#assets/img/SpaceArt/spaceAstronauts_008.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceAstronauts_009.png', width: 50, height: 50 }, 'SpaceArt-spaceAstronauts-009#assets/img/SpaceArt/spaceAstronauts_009.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceEffects_014.png', width: 50, height: 50 }, 'SpaceArt-spaceEffects-014#assets/img/SpaceArt/spaceEffects_014.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceEffects_016.png', width: 50, height: 50 }, 'SpaceArt-spaceEffects-016#assets/img/SpaceArt/spaceEffects_016.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceMissiles_003.png', width: 50, height: 50 }, 'SpaceArt-spaceMissiles-003#assets/img/SpaceArt/spaceMissiles_003.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceMissiles_008.png', width: 50, height: 50 }, 'SpaceArt-spaceMissiles-008#assets/img/SpaceArt/spaceMissiles_008.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceMissiles_013.png', width: 50, height: 50 }, 'SpaceArt-spaceMissiles-013#assets/img/SpaceArt/spaceMissiles_013.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceMissiles_023.png', width: 50, height: 50 }, 'SpaceArt-spaceMissiles-023#assets/img/SpaceArt/spaceMissiles_023.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceMissiles_025.png', width: 50, height: 50 }, 'SpaceArt-spaceMissiles-025#assets/img/SpaceArt/spaceMissiles_025.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceMissiles_037.png', width: 50, height: 50 }, 'SpaceArt-spaceMissiles-037#assets/img/SpaceArt/spaceMissiles_037.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceRocketParts_023.png', width: 50, height: 50 }, 'SpaceArt-spaceRocketParts-023#assets/img/SpaceArt/spaceRocketParts_023.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_001.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-001#assets/img/SpaceArt/spaceShips_001.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_002.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-002#assets/img/SpaceArt/spaceShips_002.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_003.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-003#assets/img/SpaceArt/spaceShips_003.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_004.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-004#assets/img/SpaceArt/spaceShips_004.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_005.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-005#assets/img/SpaceArt/spaceShips_005.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_006.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-006#assets/img/SpaceArt/spaceShips_006.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_007.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-007#assets/img/SpaceArt/spaceShips_007.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_008.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-008#assets/img/SpaceArt/spaceShips_008.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/spaceShips_009.png', width: 50, height: 50 }, 'SpaceArt-spaceShips-009#assets/img/SpaceArt/spaceShips_009.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/star_bronze.png', width: 50, height: 50 }, 'SpaceArt-star-bronze#assets/img/SpaceArt/star_bronze.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/star_gold.png', width: 50, height: 50 }, 'SpaceArt-star-gold#assets/img/SpaceArt/star_gold.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/star_silver.png', width: 50, height: 50 }, 'SpaceArt-star-silver#assets/img/SpaceArt/star_silver.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/thunderbold_silver.png', width: 50, height: 50 }, 'SpaceArt-thunderbold-silver#assets/img/SpaceArt/thunderbold_silver.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/thunderbolt_bronze.png', width: 50, height: 50 }, 'SpaceArt-thunderbolt-bronze#assets/img/SpaceArt/thunderbolt_bronze.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/thunderbolt_gold.png', width: 50, height: 50 }, 'SpaceArt-thunderbolt-gold#assets/img/SpaceArt/thunderbolt_gold.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/ufoBlue.png', width: 50, height: 50 }, 'SpaceArt-ufoBlue#assets/img/SpaceArt/ufoBlue.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/ufoGreen.png', width: 50, height: 50 }, 'SpaceArt-ufoGreen#assets/img/SpaceArt/ufoGreen.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/ufoRed.png', width: 50, height: 50 }, 'SpaceArt-ufoRed#assets/img/SpaceArt/ufoRed.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/SpaceArt/ufoYellow.png', width: 50, height: 50 }, 'SpaceArt-ufoYellow#assets/img/SpaceArt/ufoYellow.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
Blockly4kids.gameImages['TappyPlane'] = [
	[{ src: 'assets/img/TappyPlane/airPlaneBlue1.png', width: 50, height: 50 }, 'TappyPlane-airPlaneBlue1#assets/img/TappyPlane/airPlaneBlue1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/airPlaneGreen1.png', width: 50, height: 50 }, 'TappyPlane-airPlaneGreen1#assets/img/TappyPlane/airPlaneGreen1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/airPlaneRed1.png', width: 50, height: 50 }, 'TappyPlane-airPlaneRed1#assets/img/TappyPlane/airPlaneRed1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/airPlaneYellow1.png', width: 50, height: 50 }, 'TappyPlane-airPlaneYellow1#assets/img/TappyPlane/airPlaneYellow1.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/groundDirt.png', width: 50, height: 50 }, 'TappyPlane-groundDirt#assets/img/TappyPlane/groundDirt.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/groundGrass.png', width: 50, height: 50 }, 'TappyPlane-groundGrass#assets/img/TappyPlane/groundGrass.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/groundIce.png', width: 50, height: 50 }, 'TappyPlane-groundIce#assets/img/TappyPlane/groundIce.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/groundRock.png', width: 50, height: 50 }, 'TappyPlane-groundRock#assets/img/TappyPlane/groundRock.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/groundSnow.png', width: 50, height: 50 }, 'TappyPlane-groundSnow#assets/img/TappyPlane/groundSnow.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/medalBronze.png', width: 50, height: 50 }, 'TappyPlane-medalBronze#assets/img/TappyPlane/medalBronze.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/medalGold.png', width: 50, height: 50 }, 'TappyPlane-medalGold#assets/img/TappyPlane/medalGold.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/medalSilver.png', width: 50, height: 50 }, 'TappyPlane-medalSilver#assets/img/TappyPlane/medalSilver.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/puffLarge.png', width: 50, height: 50 }, 'TappyPlane-puffLarge#assets/img/TappyPlane/puffLarge.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/puffSmall.png', width: 50, height: 50 }, 'TappyPlane-puffSmall#assets/img/TappyPlane/puffSmall.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/rock.png', width: 50, height: 50 }, 'TappyPlane-rock#assets/img/TappyPlane/rock.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/rockDown.png', width: 50, height: 50 }, 'TappyPlane-rockDown#assets/img/TappyPlane/rockDown.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/rockGrass.png', width: 50, height: 50 }, 'TappyPlane-rockGrass#assets/img/TappyPlane/rockGrass.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/rockGrassDown.png', width: 50, height: 50 }, 'TappyPlane-rockGrassDown#assets/img/TappyPlane/rockGrassDown.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/rockIce.png', width: 50, height: 50 }, 'TappyPlane-rockIce#assets/img/TappyPlane/rockIce.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/rockIceDown.png', width: 50, height: 50 }, 'TappyPlane-rockIceDown#assets/img/TappyPlane/rockIceDown.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/rockSnow.png', width: 50, height: 50 }, 'TappyPlane-rockSnow#assets/img/TappyPlane/rockSnow.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/rockSnowDown.png', width: 50, height: 50 }, 'TappyPlane-rockSnowDown#assets/img/TappyPlane/rockSnowDown.png#w-90#h#cw+10#ch'],
	[{ src: 'assets/img/TappyPlane/starBronze.png', width: 50, height: 50 }, 'TappyPlane-starBronze#assets/img/TappyPlane/starBronze.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/starGold.png', width: 50, height: 50 }, 'TappyPlane-starGold#assets/img/TappyPlane/starGold.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/starSilver.png', width: 50, height: 50 }, 'TappyPlane-starSilver#assets/img/TappyPlane/starSilver.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/tap.png', width: 50, height: 50 }, 'TappyPlane-tap#assets/img/TappyPlane/tap.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/tapTick.png', width: 50, height: 50 }, 'TappyPlane-tapTick#assets/img/TappyPlane/tapTick.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/textGameOver.png', width: 50, height: 50 }, 'TappyPlane-textGameOver#assets/img/TappyPlane/textGameOver.png#Math.min(w, h)#Math.min(w, h)#cw#ch'],
	[{ src: 'assets/img/TappyPlane/textGetReady.png', width: 50, height: 50 }, 'TappyPlane-textGetReady#assets/img/TappyPlane/textGetReady.png#Math.min(w, h)#Math.min(w, h)#cw#ch']
];
